apiVersion: v3
kind: system
metadata:
  name: aaa
spec:
  components:
    - service:car-service
    - service:reservation-service
    - service:api-gateway
    - service:location-service
    - service:peer.hostname:localhost
    - service:peer.hostname:blocked-ip-address
    - service:location-service-0.0.1-snapshot
    - service:discovery-server
    - service:car-service-0.0.1-snapshot
    - datastore:peer.db.name:car_rental_db,peer.db.system:mysql
    - service:reservation-service-0.0.1-snapshot
kind: service
metadata:
  name: reservation-service
  description: Reservation App
  displayName: Reservation Service
  tags:
    - location:Gall
    - WebApp:API
    - BusinessCritical:High
    - Hosting:AWS
  owner: Reservation
  links:
    - name: Code
      type: repo
      provider: github
      url: https://github.com/Milinda96/AIOPs_Hackathon_Lab_Application
    - name: Runbook
      type: doc
      url: https://github.com/Milinda96/AIOPs_Hackathon_Lab_Application
    - name: XX
      type: other
      url: https://github.com/Milinda96/AIOPs_Hackathon_Lab_Application
  contacts:
    - name: IndikaWimalasuriya1
      type: email
      contact: wimalasuriyaib@gmail.com
  additionalOwners:
    - name: Indika
      type: Busines
    - name: Buddhi
      type: Ops
spec:
  lifecycle: Running
  tier: "1"
  languages:
    - jvm
  type: custom
extensions:
  Test.com/AppDef:
    isApplicationPubliclyAccessible: nooo
    RTO: 4 hours
    RPO: 2 hours
