apiVersion: v3
kind: service
metadata:
  name: Reservation-service
  description: Reservation App
  displayName: Reservation Service
  tags:
    - location:Gall
    - WebApp:API
  owner: Reservation
  links:
    - name: Code
      type: repo
      provider: github
      url: https://github.com/Milinda96/AIOPs_Hackathon_Lab_Application
    - name: Runbook
      type: doc
      url: https://github.com/Milinda96/AIOPs_Hackathon_Lab_Application
    - name: XX
      type: other
      url: https://github.com/Milinda96/AIOPs_Hackathon_Lab_Application
  contacts:
    - name: Indika
      type: email
      contact: wimalasuriyaib@gmail.com
  additionalOwners:
    - name: Indika
      type: Busines
    - name: Buddhi
      type: Ops
spec:
  lifecycle: Running
  tier: "1"
  languages:
    - jvm
  type: custom
extensions:
  Test.com/LocationApp:
    isApplicationPubliclyAccessible: nooo
